### ISSUE TITLE
ERROR! Unexpected Exception: No module named markupsafe

### ISSUE THREAD

**Issue by bhasselbeck** [geerlingguy/drupal-pi#16]
When running the command `ansible --version` after doing the install, I'm seeing the following output. 

``` bash
$ ansible --version
ERROR! Unexpected Exception: No module named markupsafe
the full traceback was:
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 81, in <module>
    from ansible.cli.adhoc import AdHocCLI as mycli
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/adhoc.py", line 28, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 32, in <module>
    from jinja2.exceptions import UndefinedError
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe
```

**Comment by bhasselbeck** [comment]
The temporary workaround for this is to manually install markupsafe afterwards.  `sudo pip install markupsafe`

**Comment by geerlingguy** [comment]
@bhasselbeck - Thanks for reporting this; this should not be an issue with the most recent few Ansible releases (I think there was a dependency issue around the time you ran into this, with one of the 2.1 or 2.2 releases). See: https://github.com/ansible/ansible/issues/13570
