### ISSUE TITLE
Test and build against Raspbian 10 Buster / Pi 4

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-pi#41]
Raspbian 10 Buster is here after the release of the Raspberry Pi 4 model B. So it's as good a time as any to get this project up to speed. Already did the same for the Pi Dramble, and all the upstream roles (notably docker_arm) are ready as well. Plus I now have a spare Pi 4 model B 1 GB I want to drop in as my full-time www.pidramble.com server for when the Dramble is stashed away.

**Comment by geerlingguy** [comment]
Most things work fine... but when Ansible tries running `docker-compose stop`, it returns:

```
    Traceback (most recent call last):
      File "/usr/local/bin/docker-compose", line 6, in <module>
        from compose.cli.main import main
      File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
        import docker
...
      File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
        from .ssladapter import SSLHTTPAdapter
      File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
        from backports.ssl_match_hostname import match_hostname
    ImportError: No module named ssl_match_hostname
```

There's an old open issue https://github.com/docker/docker-py/issues/1502 for this... going to dig a little. Have not seen this anywhere else.

**Comment by geerlingguy** [comment]
Hmm... I ran:

```
sudo pip install --upgrade docker
```

And during the upgrade I saw:

```
docker-compose 1.24.1 has requirement docker[ssh]<4.0,>=3.7.0, but you'll have docker 4.0.2 which is incompatible.
Installing collected packages: docker
  Found existing installation: docker 3.7.3
    Uninstalling docker-3.7.3:
      Successfully uninstalled docker-3.7.3
Successfully installed docker-4.0.2
```

I wonder if it's an issue with the current version of docker-compose's dependency list :/

**Comment by geerlingguy** [comment]
That was interesting... I found this comment () on the issue I linked earlier, which mentioned there was a Debian package which could be causing this mayhem... and that was the problem.

The fix:

```
$ sudo apt-get remove python-configparser
```

And now:

```
$ docker-compose --version
docker-compose version 1.24.1, build 4667896
```

Going to have to figure out the best way to make sure this is fixed in automation :/

**Comment by geerlingguy** [comment]
Checking on a vanilla buster install, `python-configparser` is _not_ present. So something in this playbook seems to be installing it, maybe via some dependency... i.e. when Pip is getting installed?

**Comment by geerlingguy** [comment]
So, I ran `watch "dpkg -l | grep configparser"` while running the initial setup playbook, and lo and behold, when I reached the task `geerlingguy.pip : Ensure Pip is installed.`, up popped `python-configparser`. So it's installed at that point.

I will have to see if maybe I should add a 'no-install-recommends' or something to the Pip install step.

```
$ apt-cache depends python-pip
python-pip
  Depends: ca-certificates
  Depends: python-pip-whl
  Depends: <python:any>
    python
  Depends: <python:any>
    python
  Recommends: build-essential
  Recommends: python-all-dev
  Recommends: python-setuptools
  Recommends: python-wheel
```

And:

```
$ apt-cache rdepends python-configparser
python-configparser
Reverse Depends:
  elastalert
  sagemath
  python-yapsy
  python-nipype
  python-metaconfig
  python-future
  python-flake8
  python-entrypoints
  python-custodia
  pylint
  nagios2mantis
  ibus-braille
  hinge
  eyes17
```

Strangely, I'm not sure what is getting configparser into the mix :/

**Comment by geerlingguy** [comment]
Simply installing `python-backports.ssl-match-hostname` in the required dependencies _prior to_ installing Pip seems to set things straight. Final test now, and then I'm going to tag a new happy release that seems to work great with Raspbian Buster!
